description: 's3vae prediction'

device: 'cpu' # cuda
model_save_path: '/epoch2'
filename: ''

wandb_project: 'S3VAE_seq'
wandb_group: '230213-train'

num_epochs: 2
batch_size: 16
image_shape: 1
learning_rate: 0.001
patch_size: 3
z_size: 64

margin: 1
lambda_vae: 0.2
lambda_dfp: 1
lambda_scc: 1
lambda_mi: 0
label_num: 3 # moving_mnist = 9 patch_size*patch_size
